export const INCREASE = {
  REQUEST: 'INCREASE',
  SUCCEEDED: 'INCREASE_SUCCEEDED',
  FAILED: 'INCREASE_FAILED'
}

export const DECREASE = {
  REQUEST: 'DECREASE',
  SUCCEEDED: 'DECREASE_SUCCEEDED',
  FAILED: 'DECREASE_FAILED'
}